spring:
  profiles:
    active: "secondProfile"

---
spring:
  config:
    activate:
      on-profile: "firstProfile"

app:
  num: 123
  str: hello
  list:
    - one
    - two
    - three
    - four

  myClass:
    firstParam: firstParam
    secondParam: 10s
---
spring:
  config:
    activate:
      on-profile: "secondProfile"


app:
  num: 2222
  str: hello2
  list:
    - one2
    - two2
    - three2
    - four2

  myClass:
    firstParam: firstParam2
    secondParam: 102s
